-- SELECT *
-- FROM customers
-- WHERE state = 'VA' OR state = 'GA' OR state = 'FL' 

-- THE ABOVE CAN BE SIMPLIFIED USING  IN OPERATOR

SELECT *
FROM customers
WHERE state IN ('VA','GA','FL')

-- FOR GETTING ELEMENTS IN STATE OTHER THAN THE ABOVE WE CAN USE 'NOT IN' In PLACE OF IN